export const GET_PRODUCTS = "GET_PRODUCTS";
export const POST_PRODUCTS = "POST_PRODUCTS";
export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
export const REMOVE_PRODUCTS = "REMOVE_PRODUCTS";
export const API_DATA = "API_DATA";